### ISSUE TITLE
Why not adding neovim as a recommended IDE ?

### ISSUE THREAD

**Issue by kinooyume** [gnuletik/vue-async-ce-slot#1]
As neovim also support LSP, it seems that you can have the same features with:
-  [ coc.nvim](https://github.com/neoclide/coc.nvim) + [coc-volar](https://github.com/yaegassy/coc-volar)
-  native LSP (nvim 0.5) + volar configuration (https://github.com/johnsoncodehk/volar/discussions/441)

Does something is missing in these approaches ?

**Comment by gnuletik** [comment]
This repo is a reproduction for the following issue https://github.com/vuejs/vue-next/issues/4639

I'm using coc.nvim + coc-volar already.
The README which recommends VSCode is generated by Vite through `yarn create vite`.
